version: '3'

services:
  # Api service
  musicapi:
    image: music-backend
    build:
      context: .
      dockerfile: MusicProgress/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5000:80"
    depends_on:
      - mysql-server

  # Nginx service
  proxy:
    image: nginx
    volumes: 
      - ./MusicProgress/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"

  # Database service
  mysql-server:
    image: mysql/mysql-server:8.0
    environment:
      MYSQL_DATABASE: 'music-progress'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3308:3306"