-- MySQL Script generated by MySQL Workbench
-- Fri Feb 17 16:09:27 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema audio-storage
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema audio-storage
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `audio-storage` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `audio-storage` ;

-- -----------------------------------------------------
-- Table `audio-storage`.`__efmigrationshistory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `audio-storage`.`__efmigrationshistory` (
  `MigrationId` VARCHAR(150) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `ProductVersion` VARCHAR(32) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  PRIMARY KEY (`MigrationId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `audio-storage`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `audio-storage`.`users` (
  `UserId` INT NOT NULL AUTO_INCREMENT,
  `UserName` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `Email` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `HashedPassword` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  PRIMARY KEY (`UserId`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `audio-storage`.`projects`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `audio-storage`.`projects` (
  `ProjectId` CHAR(36) CHARACTER SET 'ascii' NOT NULL,
  `Title` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `Category` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `TimeCreated` DATETIME(6) NOT NULL,
  `TimeModified` DATETIME(6) NOT NULL,
  `UserId` INT NOT NULL,
  `PosterPosition` DOUBLE NULL DEFAULT NULL,
  `IsShared` TINYINT(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (`ProjectId`),
  INDEX `IX_projects_UserId` (`UserId` ASC) VISIBLE,
  CONSTRAINT `FK_projects_users_UserId`
    FOREIGN KEY (`UserId`)
    REFERENCES `audio-storage`.`users` (`UserId`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `audio-storage`.`audios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `audio-storage`.`audios` (
  `AudioId` CHAR(36) CHARACTER SET 'ascii' NOT NULL,
  `ProjectId` CHAR(36) CHARACTER SET 'ascii' NOT NULL,
  PRIMARY KEY (`AudioId`),
  INDEX `IX_audios_ProjectId` (`ProjectId` ASC) VISIBLE,
  CONSTRAINT `FK_audios_projects_ProjectId`
    FOREIGN KEY (`ProjectId`)
    REFERENCES `audio-storage`.`projects` (`ProjectId`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `audio-storage`.`refreshtokens`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `audio-storage`.`refreshtokens` (
  `RefreshTokenId` INT NOT NULL AUTO_INCREMENT,
  `Token` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `TimeCreated` DATETIME(6) NULL DEFAULT NULL,
  `TokenExpires` DATETIME(6) NULL DEFAULT NULL,
  `UserId` INT NOT NULL,
  PRIMARY KEY (`RefreshTokenId`),
  INDEX `IX_refreshtokens_UserId` (`UserId` ASC) VISIBLE,
  CONSTRAINT `FK_refreshtokens_users_UserId`
    FOREIGN KEY (`UserId`)
    REFERENCES `audio-storage`.`users` (`UserId`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 24
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
