-- MySQL Script generated by MySQL Workbench
-- Sun Jan 22 22:04:21 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema music-progress
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema music-progress
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `music-progress` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `music-progress` ;

-- -----------------------------------------------------
-- Table `music-progress`.`__efmigrationshistory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `music-progress`.`__efmigrationshistory` (
  `MigrationId` VARCHAR(150) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  `ProductVersion` VARCHAR(32) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NOT NULL,
  PRIMARY KEY (`MigrationId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `music-progress`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `music-progress`.`users` (
  `UserId` INT NOT NULL AUTO_INCREMENT,
  `UserName` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `Email` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `HashedPassword` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  PRIMARY KEY (`UserId`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `music-progress`.`lessons`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `music-progress`.`lessons` (
  `LessonId` CHAR(36) CHARACTER SET 'ascii' NOT NULL,
  `Title` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `Category` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `UserId` INT NOT NULL,
  PRIMARY KEY (`LessonId`),
  INDEX `IX_Lessons_UserId` (`UserId` ASC) VISIBLE,
  CONSTRAINT `FK_Lessons_Users_UserId`
    FOREIGN KEY (`UserId`)
    REFERENCES `music-progress`.`users` (`UserId`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `music-progress`.`audios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `music-progress`.`audios` (
  `AudioId` CHAR(36) CHARACTER SET 'ascii' NOT NULL,
  `LessonId` CHAR(36) CHARACTER SET 'ascii' NOT NULL,
  PRIMARY KEY (`AudioId`),
  INDEX `IX_Audios_LessonId` (`LessonId` ASC) VISIBLE,
  CONSTRAINT `FK_Audios_Lessons_LessonId`
    FOREIGN KEY (`LessonId`)
    REFERENCES `music-progress`.`lessons` (`LessonId`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `music-progress`.`refreshtokens`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `music-progress`.`refreshtokens` (
  `RefreshTokenId` INT NOT NULL AUTO_INCREMENT,
  `Token` LONGTEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_0900_ai_ci' NULL DEFAULT NULL,
  `TimeCreated` DATETIME(6) NULL DEFAULT NULL,
  `TokenExpires` DATETIME(6) NULL DEFAULT NULL,
  `UserId` INT NOT NULL,
  PRIMARY KEY (`RefreshTokenId`),
  INDEX `IX_RefreshTokens_UserId` (`UserId` ASC) VISIBLE,
  CONSTRAINT `FK_RefreshTokens_Users_UserId`
    FOREIGN KEY (`UserId`)
    REFERENCES `music-progress`.`users` (`UserId`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
